I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 139, in script
    jump next_day
ScriptError: could not find label 'next_day'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 139, in script
    jump next_day
  File "C:\Users\хуй\Desktop\renpy-8.1.3-sdk\renpy\ast.py", line 1992, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\хуй\Desktop\renpy-8.1.3-sdk\renpy\script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'next_day'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
in search of a soul 1.0
Wed Jan 17 22:13:45 2024
